[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(\n  \.git\n  | \.hg\n  | \.mypy_cache\n  | \.tox\n  | \.venv\n  | _build\n  | buck-out\n  | build\n  | dist\n)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100